---
- name: install and start apache
  hosts: web
  become: yes

  tasks: 
  - name: wget epel rpm
    get_url: 
     url: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
     dest: /tmp/epel-release-7-9.noarch.rpm 

  - name: install epel repo
    yum: 
     name: /tmp/epel-release-7-9.noarch.rpm 
     state: present

  - name: install apache
    yum: name=httpd state=present
    register: stat1

  - name: start apache
    service: name=httpd state=started enabled=yes
    register: stat2

  - name: print apache dict
    debug:
     msg: "{{stat1}}" 

  - name: print apache start
    debug:
     msg: "{{stat2}}"




