---
- name: instal NodeJS
  hosts: all
  
  tasks:
  - get_url: 
     url: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
     dest: /tmp/epel-release-7-9.noarch.rpm 
    register: IR



